# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d554765f3d1175503c444598dc4f897960c759a7879e261f85db92fad2a70993db68b2a811a6ffd8e0de4d2c891a8114e88390ccc1d4940de40ad895c8deaae2

test:
  secret_key_base: 00dabdc3022305f657369c2ac8c9c99eca1e63eaef0550f0eb342829009f0707e31eee634f3311c8827831aa2544da5801ad4cf9c7399e2b6c5c4effa54e558c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
